---

- name: mongodb reload
  systemd: name={{ mongodb_daemon_name }} state=reloaded
  when: mongodb_manage_service|bool

- name: mongodb restart
  systemd: name={{ mongodb_daemon_name }} state=restarted
  when: mongodb_manage_service|bool

- name: reload systemd
  systemd:
    daemon-reload: yes
  when: mongodb_manage_service|bool

- name: restart sysfsutils
  systemd: name=sysfsutils state=restarted
