language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "cat /proc/version"
  - "sudo apt-get update"
  - "sudo apt-get install sudo git-core libcurl4-gnutls-dev libncurses5-dev"
  - "git submodule init"
  - "git submodule update"
  - "sudo ./build-install.sh -l"
  - "sudo su - canopsis -c \"hypcontrol start\""
# command to run tests
script:
 - "sudo su - canopsis -c \"unittest.sh\""
