---
version: '2'
volumes:
  mongodbdata:
    driver: local
  rabbitmqdata:
    driver: local

services:
  rabbitmq:
    image: rabbitmq:${RABBITMQ_TAG}
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 2g
    oom_score_adj: -1000
    environment:
      - RABBITMQ_DEFAULT_USER=cpsrabbit
      - RABBITMQ_DEFAULT_PASS=canopsis
      - RABBITMQ_DEFAULT_VHOST=canopsis
  mongodb:
    image: mongo:${MONGODB_TAG}
    env_file: compose.mongo.env
    ports:
      - "27027:27017"
    volumes:
      - mongodbdata:/data/db
      - "./files/mongo/:/docker-entrypoint-initdb.d"
    restart: unless-stopped
    mem_limit: 3g
    mem_reservation: 3g
    oom_score_adj: -1000
    command: '--wiredTigerCacheSizeGB 2560'
  redis:
    image: redis:${REDIS_TAG}
    restart: unless-stopped
    ports:
      - 6379:6379
  nginx:
    image: canopsis/nginx:${CANOPSIS_IMAGE_TAG}
    ports:
      - "80:80"
    env_file:
      - compose.env
    depends_on:
      - "api"
    restart: unless-stopped
  provisioning:
    image: canopsis/canopsis-prov:${CANOPSIS_IMAGE_TAG}
    environment:
      - CPS_EDITION=community
    env_file:
      - compose.env
    depends_on:
      - "mongodb"
    restart: "no"
  action:
    image: canopsis/engine-action:${CANOPSIS_IMAGE_TAG}
    env_file:
      - compose.env
    restart: unless-stopped
    command: /engine-action
  api:
    image: canopsis/canopsis-api:${CANOPSIS_IMAGE_TAG}
    ports:
      - "8082:8082"
    env_file:
      - compose.env
    depends_on:
      - "oldapi"
    restart: unless-stopped
    command: /canopsis-api
  axe:
    image: canopsis/engine-axe:${CANOPSIS_IMAGE_TAG}
    env_file:
      - compose.env
    restart: unless-stopped
    command: /engine-axe
  che:
    image: canopsis/engine-che:${CANOPSIS_IMAGE_TAG}
    env_file:
      - compose.env
    restart: unless-stopped
    command: /engine-che
  fifo:
    image: canopsis/engine-fifo:${CANOPSIS_IMAGE_TAG}
    env_file:
      - compose.env
    restart: unless-stopped
    command: /engine-fifo
  pbehavior:
    image: canopsis/engine-pbehavior:${CANOPSIS_IMAGE_TAG}
    env_file:
      - compose.env
    restart: unless-stopped
    command: /engine-pbehavior
  service:
    image: canopsis/engine-service:${CANOPSIS_IMAGE_TAG}
    env_file:
      - compose.env
    restart: unless-stopped
  oldapi:
    image: canopsis/canopsis-core:${CANOPSIS_IMAGE_TAG}
    env_file:
      - compose.env
    environment:
      - CPS_OLD_API=1
    depends_on:
      - "mongodb"
    ports:
      - "8081:8081"
    links:
      - mongodb
      - rabbitmq
    restart: unless-stopped
  reconfigure:
    image: canopsis/canopsis-reconfigure:${CANOPSIS_IMAGE_TAG}
    depends_on:
      - "rabbitmq"
      - "mongodb"
    env_file:
      - compose.env
