---

dependencies: []

galaxy_info:
  author: Sergei Antipov
  company: Self-employed
  description: Manage MongoDB with authentication and replica sets
  license: GPLv2
  min_ansible_version: 2.8
  platforms:
  - name: EL
    versions:
      - 7
  galaxy_tags:
  - database
  - database:nosql
